### ISSUE TITLE
Linux Serial Port gets unmapped on server reboot

### ISSUE THREAD

**Issue by dsecca-mss** [rchovan/npreal2#10]
Hello,

I have the npreal2 driver kernel_5.x.x version installed on an Ubuntu 20.04.1 LTS server. The driver is mapped to a serial port /dev/ttyMPLT. When the server is rebooted, we get the error "No such device or address: '/dev/ttyMPLT'" when trying to connect to the serial port. The current workaround we have is to reinstall the npreal2 driver however this error message consistently reappears after the server has been rebooted.

I have checked the system requirements in the README.txt file and all our packages match the versions outlined in there.

Do you know what can be causing this issue?

Thanks,
David

**Comment by rchovan** [comment]
Hi, 
from my experiences, I'm running mxloadsvr on startup. I put it to my /etc/rc.local file. I can't help you more with this issue, because this driver is from 2019. I'm not a developer of this driver. But if you need support, you can ask here > https://www.moxa.com/en/support

**Comment by dsecca-mss** [comment]
Hello,

Thanks for your suggestion. It seems to work on our side! I will note the support link you gave me in the event I have further questions.

Thanks,
David
