### ISSUE TITLE
random npreal2d driver oddities

### ISSUE THREAD

**Issue by keimond** [rchovan/npreal2#4]
Hello, we are having problems with a port failing from time to time.. it's a MOXA that we talk to via TCP.. it has 16 ports.. all ports but the one work.. when it fails, if I try to use modpoll, it says the port can't be opened.. but as soon as I run ./mxinst module and reload the module, I can run modpoll and get data from the port.  I was curious if you guys knew what I should be looking for in terms of good troubleshooting steps ? I'm currently running an strace waiting for the next failure (which is very random)

CentOS 6.7, 2.6.32-642.1.1.el6.x86_64, using npreal2 Ver1.18.33 Build 14060316

**Comment by rchovan** [comment]
Hi, 
sorry, I'm not author of npreal driver. You should contact Moxa support. This repository is fork of original moxa driver. I had problem with kernel version 3.15 and ask community for help. One user created patch 1538091 and I have merged it .

**Comment by keimond** [comment]
oh bummer ok didn't know how much work you guys had put in to it. Not a problem. Thanks!
