### ISSUE TITLE
Deprecated documentation

### ISSUE THREAD

**Issue by YandexWillKillYou** [rchovan/npreal2#5]

**Comment by YandexWillKillYou** [comment]
This is header of /usr/lib/npreal2d/driver/npreal2d.cf

#=========================================================#
#   This configuration file is created by Moxa NPort      #
#   Administrator Program automatically, please do not    #
#   modify this file by yourself.                         #
#=========================================================#

This is 7b from README
After entering the directory "/usr/lib/npreal2/driver", you can modify 
      "npreal2d.cf" to map NPort serial ports to tty ports, and then execute 
      "mxloadsvr" to activate the modifications.

By the way, when i change npreal2d.cf manually, it suddenly emptifies, so documentation is deprecated

**Comment by rchovan** [comment]
I'm not author of this driver. This is my shared repo with driver sources
