### ISSUE TITLE
mxinst polling issue

### ISSUE THREAD

**Issue by robycremo** [rchovan/npreal2#6]
I am having this issue compiling `./mxinst polling`
[fail.txt](https://github.com/rchovan/npreal2/files/4291738/fail.txt)
,  without using polling switch i can compile driver 
[good.txt](https://github.com/rchovan/npreal2/files/4291750/good.txt)

```
make -C /lib/modules/4.15.0-88-generic/build M=/home/XXXXX/npreal2 modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-88-generic'
  CC [M]  /home/XXXXX/npreal2/npreal2.o
In file included from /home/XXXXX/npreal2/npreal2.c:106:0:
/home/XXXXX/npreal2/npreal2.c: In function ‘npreal_startup’:
/home/XXXXX/npreal2/npreal2.c:1913:84: error: expected ‘)’ before ‘info’
     DBGPRINT(MX_DEBUG_ERROR, "(P%02d)LOCAL_CMD_TTY_USED shows connection failed\n" info->port);
```

**Comment by rchovan** [comment]
Hi, 
latest version is for actual kernel. Try branch for kernel 4.x.x  https://github.com/rchovan/npreal2/tree/kernel_4.x.x

**Comment by rchovan** [comment]
NOT MAINTAINED ANYMORE

due to lack of time and lot of issues I've stopped using MONA TTY server. I've switched to USB-1Wire convertor.
If you have issues, look at the AUR repository, it is still maintained, and you can apply patches manually.
