### ISSUE TITLE
moxa driver on Kernel 4.4.179; Machine aarch64.

### ISSUE THREAD

**Issue by alex-nkz** [rchovan/npreal2#9]
Why this error?
===============================================================================
Copyright (C) 2002-2015  Moxa Inc.
All Rights Reserved.

MOXA NPort Server Real TTY Driver Ver1.18.65 Installation.
System Information: Kernel 4.4.179; Machine aarch64.
===============================================================================

Building driver...

If you want to use secure communication with target,
you might choose [y] to enable the SSL function.
Note: This function support RealCOM with secure mode only.
Do you want to enable secure function? [y/N].
n
make -C /lib/modules/4.4.179/build SUBDIRS=/root/MoxaNPort/moxa/kernel3.x modules
make[1]: *** /lib/modules/4.4.179/build: No such file or directory.  Stop.
Makefile:63: recipe for target 'module' failed
make: *** [module] Error 2
Check Driver...
FAILED !!!

Install Not Completed !

root@NanoPi-M4:~/MoxaNPort/moxa/kernel3.x#

**Comment by rchovan** [comment]
NOT MAINTAINED ANYMORE

due to lack of time and lot of issues I've stopped using MOXA TTY server. I've switched to USB-1Wire convertor.
If you have issues, look at the AUR repository, it is still maintained, and you can apply patches manually.
